<?php

namespace ContainerJETt7tz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOccasionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..K61wtU.App\Entity\Occasion' shared service.
     *
     * @return \App\Entity\Occasion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..K61wtU": it references class "App\\Entity\\Occasion" but no such service exists.');
    }
}
