<?php

namespace ContainerYir9dbp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S54sxQjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S54sxQj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S54sxQj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'status' => ['privates', '.errored..service_locator.S54sxQj.App\\Entity\\Status', NULL, 'Cannot autowire service ".service_locator.S54sxQj": it references class "App\\Entity\\Status" but no such service exists.'],
            'statusRepository' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'status' => 'App\\Entity\\Status',
            'statusRepository' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
