<?php

namespace ContainerYir9dbp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarousel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bKrCQJk.App\Entity\Carousel' shared service.
     *
     * @return \App\Entity\Carousel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bKrCQJk": it references class "App\\Entity\\Carousel" but no such service exists.');
    }
}
