<?php

namespace ContainerRgD7lqK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProfileType' shared autowired service.
     *
     * @return \App\Form\ProfileType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProfileType'] = new \App\Form\ProfileType();
    }
}
