<?php

namespace ContainerRgD7lqK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPicturePositionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PicturePositionType' shared autowired service.
     *
     * @return \App\Form\PicturePositionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PicturePositionType'] = new \App\Form\PicturePositionType();
    }
}
