<?php

namespace Container3hWgfTK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfile3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bgwvv6M.App\Entity\Profile' shared service.
     *
     * @return \App\Entity\Profile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bgwvv6M": it references class "App\\Entity\\Profile" but no such service exists.');
    }
}
