<?php

namespace ContainerQkEeMkb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPicture2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.isuZJzD.App\Entity\Picture' shared service.
     *
     * @return \App\Entity\Picture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.isuZJzD": it references class "App\\Entity\\Picture" but no such service exists.');
    }
}
