<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgD7lqK\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgD7lqK/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRgD7lqK.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRgD7lqK\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRgD7lqK\App_KernelProdContainer([
    'container.build_hash' => 'RgD7lqK',
    'container.build_id' => '7dd1228e',
    'container.build_time' => 1666343674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgD7lqK');
