<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwpcMZ4\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwpcMZ4/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPwpcMZ4.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPwpcMZ4\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPwpcMZ4\App_KernelProdContainer([
    'container.build_hash' => 'PwpcMZ4',
    'container.build_id' => '634de280',
    'container.build_time' => 1668079704,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwpcMZ4');
