<?php

namespace ContainerCHSe15Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProfileControllerService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AdminProfileController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/AdminProfileController.php';

        $container->services['App\\Controller\\Admin\\AdminProfileController'] = $instance = new \App\Controller\Admin\AdminProfileController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Admin\\AdminProfileController', $container));

        return $instance;
    }
}
