<?php

namespace ContainerCHSe15Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1Wt5IVP.App\Entity\Gallery' shared service.
     *
     * @return \App\Entity\Gallery
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1Wt5IVP": it references class "App\\Entity\\Gallery" but no such service exists.');
    }
}
