<?php

namespace ContainerCHSe15Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfile2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ahMh5b4.App\Entity\Profile' shared service.
     *
     * @return \App\Entity\Profile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ahMh5b4": it references class "App\\Entity\\Profile" but no such service exists.');
    }
}
