<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kd9dySWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.kd9dySW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kd9dySW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'occasionRepository' => ['privates', 'App\\Repository\\OccasionRepository', 'getOccasionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'occasionRepository' => 'App\\Repository\\OccasionRepository',
        ]);
    }
}
