<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminStatusTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Admin\AdminStatusType' shared autowired service.
     *
     * @return \App\Form\Admin\AdminStatusType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Admin\\AdminStatusType'] = new \App\Form\Admin\AdminStatusType();
    }
}
