<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CarouselType' shared autowired service.
     *
     * @return \App\Form\CarouselType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CarouselType'] = new \App\Form\CarouselType();
    }
}
