<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._F_JZ9H.App\Entity\Carousel' shared service.
     *
     * @return \App\Entity\Carousel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._F_JZ9H": it references class "App\\Entity\\Carousel" but no such service exists.');
    }
}
