<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPictureTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PictureType' shared autowired service.
     *
     * @return \App\Form\PictureType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PictureType'] = new \App\Form\PictureType();
    }
}
