<?php

namespace ContainerPwpcMZ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProfileRepository' shared autowired service.
     *
     * @return \App\Repository\ProfileRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProfileRepository'] = new \App\Repository\ProfileRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
