<?php

namespace ContainerKzHz7Zx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOccasion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7153S2w.App\Entity\Occasion' shared service.
     *
     * @return \App\Entity\Occasion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7153S2w": it references class "App\\Entity\\Occasion" but no such service exists.');
    }
}
