<?php

namespace ContainerLCgmneX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Admin\AdminUserType' shared autowired service.
     *
     * @return \App\Form\Admin\AdminUserType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Admin/AdminUserType.php';

        return $container->privates['App\\Form\\Admin\\AdminUserType'] = new \App\Form\Admin\AdminUserType();
    }
}
