<?php

namespace ContainerLCgmneX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPictureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UHAlgBm.App\Entity\Picture' shared service.
     *
     * @return \App\Entity\Picture
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UHAlgBm": it references class "App\\Entity\\Picture" but no such service exists.');
    }
}
