<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKzHz7Zx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKzHz7Zx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKzHz7Zx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKzHz7Zx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKzHz7Zx\App_KernelDevDebugContainer([
    'container.build_hash' => 'KzHz7Zx',
    'container.build_id' => '09a2f483',
    'container.build_time' => 1669207143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKzHz7Zx');
