<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ8bRgzx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ8bRgzx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ8bRgzx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ8bRgzx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ8bRgzx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z8bRgzx',
    'container.build_id' => 'b83fa456',
    'container.build_time' => 1667574752,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ8bRgzx');
